server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
##spring.cloud.config.server.git.uri propertie indicate where are we going to get the config properties
## default-label indicates which branch will be the default to get config properties
spring:
  application:
    name: config-service ❷
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sibokdev/config-repo
          default-label: main
          ## next properties help in case of remote repo failure
          timeout: 5 #Time limit to establish a connection with the remote repository
          clone-on-start: true #Clones the remote repository locally on startup
          force-pull: true #Forces pulling the remote repository and discarding any local changes